---
proxy-groups:
- name: MULTI-LB
  type: load-balance
  strategy: consistent-hashing
  disable-udp: true
  proxies:
  - LB-SS
  - LB-TR
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: LB-SS
  type: url-test
  disable-udp: true
  use:
  - Proxy-SS
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: '150'
- name: LB-TR
  type: url-test
  disable-udp: true
  use:
  - Proxy-TR
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: '150'
rules:
- RULE-SET,R-UMUM,LB-TR
- RULE-SET,R-STREAMING,MULTI-LB
- RULE-SET,R-SOSMED,LB-SS
- RULE-SET,R-GAMING,MULTI-LB
dns:
  nameserver:
  - https://dns.adguard-dns.com/dns-query
  - tls://dns.adguard-dns.com:853
  - 114.114.114.114
  - 8.8.8.8
  - 1.1.1.1
  - https://dns.google/dns-query
  - tls://dns.google
  - https://dns.quad9.net/dns-query
  - tls://9.9.9.9:853
  - https://cloudflare-dns.com/dns-query
  - tls://1dot1dot1dot1.cloudflare-dns.com
  fallback:
  - https://dns.adguard-dns.com/dns-query
  - tls://dns.adguard-dns.com:853
  - https://dns.google/dns-query
  - tls://dns.google
  - https://dns.quad9.net/dns-query
  - tls://149.112.112.112:853
  - tls://one.one.one.one:853
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  fake-ip-filter:
  - "*.lan"
  - time.windows.com
  - time.nist.gov
  - time.apple.com
  - time.asia.apple.com
  - "*.ntp.org.cn"
  - "*.openwrt.pool.ntp.org"
  - time1.cloud.tencent.com
  - time.ustc.edu.cn
  - 0.id.pool.ntp.org
  - 1.id.pool.ntp.org
  - 2.id.pool.ntp.org
  - 3.id.pool.ntp.org
  - "+.*"
  default-nameserver:
  - 94.140.14.14
  - 192.168.1.1
  - 114.114.114.114
  - 8.8.8.8
  use-hosts: true
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: '123456'
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: false
profile:
  store-selected: true
  store-fake-ip: true
proxy-providers:
  Proxy-SS:
    type: file
    path: "./proxy_provider/Akun_SS.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  Proxy-TR:
    type: file
    path: "./proxy_provider/Akun_TR.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
rule-providers:
  R-UMUM:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/klik-on/clash/main/rule_provider/umum.yaml
    path: "./rule_provider/umum.yaml"
    interval: 86400
  R-STREAMING:
    type: http
    url: https://raw.githubusercontent.com/klik-on/clash/main/rule_provider/streaming.yaml
    behavior: classical
    path: "./rule_provider/streaming.yaml"
    interval: 86400
  R-SOSMED:
    type: http
    url: https://raw.githubusercontent.com/klik-on/clash/main/rule_provider/sosmed.yaml
    behavior: classical
    path: "./rule_provider/sosmed.yaml"
    interval: 86400
  R-GAMING:
    type: http
    url: https://raw.githubusercontent.com/klik-on/clash/main/game_rules/gaming.yaml
    behavior: classical
    path: "./game_rules/gaming.yaml"
    interval: 86400
hosts:
experimental:
  sniff-tls-sni: true
authentication:
- Clash:ZOR2q1IR

